"""deletando entidade tipo_arquivo do banco

Revision ID: 125baa17c3a4
Revises: b04e37797f78
Create Date: 2025-08-15 11:28:30.687430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '125baa17c3a4'
down_revision: Union[str, None] = 'b04e37797f78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('arquivo_tipo_arquivo_id_fkey', 'arquivo', type_='foreignkey')
    op.drop_table('tipo_arquivo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('arquivo_tipo_arquivo_id_fkey', 'arquivo', 'tipo_arquivo', ['tipo_arquivo_id'], ['id'])
    op.create_table('tipo_arquivo',
    sa.Column('id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('contexto', postgresql.ENUM('PROPONENTE', 'PROJETO', 'DADOS_BANCARIOS', 'EDITAL', 'GERENCIAMENTO_META', 'GERENCIAMENTO_QUALITATIVO', 'GERENCIAMENTO_CONTRAPARTIDA', name='tipoarquivocontexto'), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('info', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tipo_arquivo_pkey'),
    sa.UniqueConstraint('descricao', name='tipo_arquivo_descricao_key')
    )
    # ### end Alembic commands ###
