"""iniciando

Revision ID: 27e5f2c77d84
Revises: 
Create Date: 2025-04-07 22:18:28.657887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27e5f2c77d84'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gerenciamento_comentario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comentario', sa.String(length=100), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('gerenciamento_proposta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('trimestre_de_referencia', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.Enum('TRIMESTRAL', 'FINAL', name='tipogerenciamento'), nullable=False),
    sa.Column('proposta_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('gerenciamento_comentario_association',
    sa.Column('gerenciamento_id', sa.Integer(), nullable=False),
    sa.Column('comentario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comentario_id'], ['gerenciamento_comentario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gerenciamento_id'], ['gerenciamento_proposta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('gerenciamento_id', 'comentario_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gerenciamento_comentario_association')
    op.drop_table('gerenciamento_proposta')
    op.drop_table('gerenciamento_comentario')
    # ### end Alembic commands ###
