"""Add Tabela Gerenciamento Qualitativo

Revision ID: 3d9ce382ab8e
Revises: 581ca50840a7
Create Date: 2025-04-22 16:41:49.316725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d9ce382ab8e'
down_revision: Union[str, None] = '581ca50840a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gerenciamento_qualitativo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('acoes_realizadas', sa.String(length=500), nullable=False),
    sa.Column('acoes_previstas', sa.String(length=500), nullable=False),
    sa.Column('visao_proponente', sa.String(length=500), nullable=False),
    sa.Column('gerenciamento_proposta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gerenciamento_proposta_id'], ['gerenciamento_proposta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('gerenciamentoQualitativo_comentario_association',
    sa.Column('gerenciamentoQualitativo_id', sa.Integer(), nullable=False),
    sa.Column('comentario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comentario_id'], ['gerenciamento_comentario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gerenciamentoQualitativo_id'], ['gerenciamento_qualitativo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('gerenciamentoQualitativo_id', 'comentario_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gerenciamentoQualitativo_comentario_association')
    op.drop_table('gerenciamento_qualitativo')
    # ### end Alembic commands ###
