"""Criando Banco

Revision ID: 581ca50840a7
Revises: 
Create Date: 2025-04-21 04:10:17.069843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '581ca50840a7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gerenciamento_comentario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comentario', sa.String(length=100), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('gerenciamento_proposta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trimestre_de_referencia', sa.Date(), nullable=False),
    sa.Column('tipo', sa.Enum('TRIMESTRAL', 'FINAL', name='tipogerenciamento'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('proposta_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('gerenciamentoProposta_comentario_association',
    sa.Column('gerenciamentoProposta_id', sa.Integer(), nullable=False),
    sa.Column('comentario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comentario_id'], ['gerenciamento_comentario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gerenciamentoProposta_id'], ['gerenciamento_proposta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('gerenciamentoProposta_id', 'comentario_id')
    )
    op.create_table('gerenciamento_meta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ordem', sa.SmallInteger(), nullable=True),
    sa.Column('alcancado', sa.Integer(), nullable=False),
    sa.Column('gerenciamento_proposta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gerenciamento_proposta_id'], ['gerenciamento_proposta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('gerenciamento_quantitativo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('educacao_financeira_impactados', sa.Integer(), nullable=False),
    sa.Column('educacao_financeira_alcancados', sa.Integer(), nullable=False),
    sa.Column('geracao_renda_postos_trabalho_gerados', sa.Integer(), nullable=False),
    sa.Column('alcance_marca_pessoas_alcancadas_publicacao_digitais', sa.Integer(), nullable=False),
    sa.Column('pessoas_alcancadas', sa.Integer(), nullable=False),
    sa.Column('pessoas_impactadas', sa.Integer(), nullable=False),
    sa.Column('gerenciamento_proposta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gerenciamento_proposta_id'], ['gerenciamento_proposta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('gerenciamentoQuantitativo_comentario_association',
    sa.Column('gerenciamentoQuantitativo_id', sa.Integer(), nullable=False),
    sa.Column('comentario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comentario_id'], ['gerenciamento_comentario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gerenciamentoQuantitativo_id'], ['gerenciamento_quantitativo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('gerenciamentoQuantitativo_id', 'comentario_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gerenciamentoQuantitativo_comentario_association')
    op.drop_table('gerenciamento_quantitativo')
    op.drop_table('gerenciamento_meta')
    op.drop_table('gerenciamentoProposta_comentario_association')
    op.drop_table('gerenciamento_proposta')
    op.drop_table('gerenciamento_comentario')
    # ### end Alembic commands ###
