"""criando o banco

Revision ID: 618493c62f60
Revises: 
Create Date: 2025-05-09 01:56:50.899096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '618493c62f60'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gerenciamento_comentario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comentario', sa.String(length=100), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gerenciamento_proposta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trimestre_de_referencia', sa.Date(), nullable=False),
    sa.Column('tipo', sa.Enum('TRIMESTRAL', 'FINAL', name='tipogerenciamento'), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('proposta_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_arquivo',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('contexto', sa.Enum('PROPONENTE', 'PROJETO', 'DADOS_BANCARIOS', 'EDITAL', 'GERENCIAMENTO_META', 'GERENCIAMENTO_QUALITATIVO', 'GERENCIAMENTO_CONTRAPARTIDA', name='tipoarquivocontexto'), nullable=False),
    sa.Column('descricao', sa.String(length=120), nullable=False),
    sa.Column('info', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descricao')
    )
    op.create_table('tipo_categorizacao_beneficiario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('info', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arquivo',
    sa.Column('arquivo_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('extensao', sa.String(length=4), nullable=False),
    sa.Column('tamanho', sa.Integer(), nullable=False),
    sa.Column('uri', sa.String(length=250), nullable=False),
    sa.Column('tipo_arquivo_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['tipo_arquivo_id'], ['tipo_arquivo.id'], ),
    sa.PrimaryKeyConstraint('arquivo_id')
    )
    op.create_table('categorizacao_beneficiario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_categ_beneficiario_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['tipo_categ_beneficiario_id'], ['tipo_categorizacao_beneficiario.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo_categ_beneficiario_id', 'valor', name='categorizacao_beneficiario_tipo_valor_uq')
    )
    op.create_table('gerenciamento_contrapartida',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('observacao', sa.String(length=300), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PLANEJADO', 'EM_APROVACAO', 'EM_AJUSTE', 'ENTREGUE', 'JUSTIFICADA', 'NAO_ENTREGUE', name='statusgereciamentocontrapartida'), nullable=False),
    sa.Column('proposta_contrapartida_id', sa.Integer(), nullable=False),
    sa.Column('gerenciamento_proposta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gerenciamento_proposta_id'], ['gerenciamento_proposta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gerenciamento_meta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ordem', sa.SmallInteger(), nullable=True),
    sa.Column('alcancado', sa.Integer(), nullable=False),
    sa.Column('gerenciamento_proposta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gerenciamento_proposta_id'], ['gerenciamento_proposta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gerenciamento_proposta_comentario_association',
    sa.Column('gerenciamentoProposta_id', sa.Integer(), nullable=False),
    sa.Column('comentario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comentario_id'], ['gerenciamento_comentario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gerenciamentoProposta_id'], ['gerenciamento_proposta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('gerenciamentoProposta_id', 'comentario_id')
    )
    op.create_table('gerenciamento_qualitativo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('acoes_realizadas', sa.String(length=500), nullable=False),
    sa.Column('acoes_previstas', sa.String(length=500), nullable=False),
    sa.Column('visao_proponente', sa.String(length=500), nullable=False),
    sa.Column('gerenciamento_proposta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gerenciamento_proposta_id'], ['gerenciamento_proposta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gerenciamento_quantitativo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('educacao_financeira_impactados', sa.Integer(), nullable=False),
    sa.Column('educacao_financeira_alcancados', sa.Integer(), nullable=False),
    sa.Column('geracao_renda_postos_trabalho_gerados', sa.Integer(), nullable=False),
    sa.Column('alcance_marca_pessoas_alcancadas_publicacao_digitais', sa.Integer(), nullable=False),
    sa.Column('pessoas_alcancadas', sa.Integer(), nullable=False),
    sa.Column('pessoas_impactadas', sa.Integer(), nullable=False),
    sa.Column('gerenciamento_proposta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gerenciamento_proposta_id'], ['gerenciamento_proposta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gerenciamento_caracterizacao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('gerenciamento_quantitativo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gerenciamento_quantitativo_id'], ['gerenciamento_quantitativo.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gerenciamento_contrapartida_admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('justificativa', sa.String(length=150), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('gerenciamento_contrapartida_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gerenciamento_contrapartida_id'], ['gerenciamento_contrapartida.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gerenciamento_contrapartida_arquivo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gerenciamento_contrapartida_id', sa.Integer(), nullable=False),
    sa.Column('arquivo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['arquivo_id'], ['arquivo.arquivo_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gerenciamento_contrapartida_id'], ['gerenciamento_contrapartida.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gerenciamento_meta_arquivo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gerenciamento_meta_id', sa.Integer(), nullable=False),
    sa.Column('arquivo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['arquivo_id'], ['arquivo.arquivo_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gerenciamento_meta_id'], ['gerenciamento_meta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gerenciamento_qualitativo_arquivo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gerenciamento_qualitativo_id', sa.Integer(), nullable=False),
    sa.Column('arquivo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['arquivo_id'], ['arquivo.arquivo_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gerenciamento_qualitativo_id'], ['gerenciamento_qualitativo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gerenciamento_qualitativo_comentario_association',
    sa.Column('gerenciamentoQualitativo_id', sa.Integer(), nullable=False),
    sa.Column('comentario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comentario_id'], ['gerenciamento_comentario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gerenciamentoQualitativo_id'], ['gerenciamento_qualitativo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('gerenciamentoQualitativo_id', 'comentario_id')
    )
    op.create_table('gerenciamento_quantitativo_comentario_association',
    sa.Column('gerenciamentoQuantitativo_id', sa.Integer(), nullable=False),
    sa.Column('comentario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comentario_id'], ['gerenciamento_comentario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gerenciamentoQuantitativo_id'], ['gerenciamento_quantitativo.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('gerenciamentoQuantitativo_id', 'comentario_id')
    )
    op.create_table('gerenciamento_beneficiario_categorizacao',
    sa.Column('gerenciamento_beneficiario_id', sa.Integer(), nullable=False),
    sa.Column('categorizacao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['categorizacao_id'], ['categorizacao_beneficiario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gerenciamento_beneficiario_id'], ['gerenciamento_caracterizacao.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('gerenciamento_beneficiario_id', 'categorizacao_id'),
    sa.UniqueConstraint('gerenciamento_beneficiario_id', 'categorizacao_id', name='gerenciamento_beneficiario_categorizacao_uq')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gerenciamento_beneficiario_categorizacao')
    op.drop_table('gerenciamento_quantitativo_comentario_association')
    op.drop_table('gerenciamento_qualitativo_comentario_association')
    op.drop_table('gerenciamento_qualitativo_arquivo')
    op.drop_table('gerenciamento_meta_arquivo')
    op.drop_table('gerenciamento_contrapartida_arquivo')
    op.drop_table('gerenciamento_contrapartida_admin')
    op.drop_table('gerenciamento_caracterizacao')
    op.drop_table('gerenciamento_quantitativo')
    op.drop_table('gerenciamento_qualitativo')
    op.drop_table('gerenciamento_proposta_comentario_association')
    op.drop_table('gerenciamento_meta')
    op.drop_table('gerenciamento_contrapartida')
    op.drop_table('categorizacao_beneficiario')
    op.drop_table('arquivo')
    op.drop_table('tipo_categorizacao_beneficiario')
    op.drop_table('tipo_arquivo')
    op.drop_table('gerenciamento_proposta')
    op.drop_table('gerenciamento_comentario')
    # ### end Alembic commands ###
